#!/usr/bin/env python3

# Copyright 2017-2020 Andrew Myers, Axel Huebl, Burlen Loring
# Maxence Thevenet, Remi Lehe
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

# -*- coding: utf-8 -*-
#
# WarpX documentation build configuration file, created by
# sphinx-quickstart on Tue Mar  7 22:08:26 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import json
import os
import subprocess
import sys
import urllib.request

import pybtex.plugin
import sphinx_rtd_theme  # noqa
from pybtex.style.formatting.unsrt import Style as UnsrtStyle

module_path = os.path.dirname(os.path.abspath(__file__))
checksum_path = os.path.join(module_path, "../../Regression/Checksum")
sys.path.insert(0, checksum_path)

# Modify sys.path to use custom extension in _ext
_ext_path = os.path.join(module_path, "_ext")
sys.path.insert(0, _ext_path)


def download_with_headers(url, filename):
    """Download a file with proper User-Agent header to avoid 403 errors."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "WarpX-docs-builder"})
        with urllib.request.urlopen(req) as response:
            with open(filename, "wb") as f:
                f.write(response.read())
    except Exception as e:
        print(f"Could not download {filename} from {url}: {e}")
        print("Continuing build without cross-reference file...")


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinx_design",
    "breathe",
    "myst_parser",
    "sphinxcontrib.bibtex",
    "sphinxcontrib.googleanalytics",
    "sphinxcontrib.autodoc_pydantic",
    "parmparse",
]

# Document members (incl. pydantic fields) so the auto-generated parameter list
# (from each Field(description=...)) is rendered for every documented class.
# ``undoc-members`` is required because pydantic fields carry no __doc__ (their text
# lives in Field(description=...)); without it autodoc skips them as "undocumented".
# ``model_post_init`` is an internal initialization hook (pydantic generates it for models
# with private attributes), not a user-facing method.
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "exclude-members": "model_post_init",
}

# -- autodoc-pydantic ---------------------------------------------------------
# The PICMI bindings are pydantic models; render their (and the warpx_ extension)
# fields cleanly, hiding the pydantic internals.
# Hide the (very long) full field list from the class signature; the parameters are
# documented individually as the field list below instead.
autodoc_pydantic_model_hide_paramlist = True
autodoc_pydantic_model_show_json = False
autodoc_pydantic_model_show_config_summary = False
autodoc_pydantic_model_show_validator_summary = False
autodoc_pydantic_model_show_validator_members = False
autodoc_pydantic_model_show_field_summary = False
# Group members by type so all parameters (pydantic fields) are listed first as one
# block, followed by methods and properties (mirrors the old "Parameters first" layout).
autodoc_pydantic_model_member_order = "groupwise"
autodoc_pydantic_field_list_validators = False
autodoc_pydantic_field_show_constraints = False
autodoc_pydantic_field_show_default = True
# Render each field as "parameter <name>" instead of the default "field <name>".
autodoc_pydantic_field_signature_prefix = "parameter"
autodoc_pydantic_field_show_alias = True
autodoc_pydantic_field_swap_name_and_alias = True

# Google Analytics
googleanalytics_id = "G-QZGY5060MZ"
googleanalytics_enabled = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# Relative path to bibliography file, bibliography style
bibtex_bibfiles = ["refs.bib"]


# An brief introduction to custom BibTex formatting can be found in the Sphinx documentation:
# https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#bibtex-custom-formatting
#
# More details can be gleaned from looking at the pybtex dist-package files.
# Some examples include the following:
# BaseStyle class in pybtex/style/formatting/__init__.py
# UnsrtStyle class in pybtex/style/formating/unsrt.py
class WarpXBibStyle(UnsrtStyle):
    # This option makes the family name, i.e, "last" name, of an author to appear first.
    # default_name_style = 'lastfirst'

    def __init__(self, *args, **kwargs):
        # This option makes the given names of an author abbreviated to just initials.
        # Example: "Jean-Luc" becomes "J.-L."
        # Set 'abbreviate_names' to True before calling the superclass (BaseStyle class) initializer
        kwargs["abbreviate_names"] = True
        super().__init__(*args, **kwargs)


pybtex.plugin.register_plugin("pybtex.style.formatting", "warpxbibstyle", WarpXBibStyle)

bibtex_default_style = "warpxbibstyle"

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = [".rst", ".md"]

# Resolve MyST's Markdown cross-references against Sphinx's standard labels.
myst_ref_domains = ["std"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "WarpX"
copyright = "2017-2021, WarpX collaboration"
author = "WarpX collaboration"

# Parse WarpX version information
dependencies_file = "../../dependencies.json"
with open(dependencies_file, "r") as file:
    dependencies_data = json.load(file)
warpx_version = dependencies_data.get("version_warpx")

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = warpx_version
# The full version, including alpha/beta/rc tags.
release = warpx_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_logo = "_static/WarpX_Logo.png"

numfig = True
math_eqref_format = "{number}"
numfig_format = {
    "figure": "Fig. %s",
    "table": "Table %s",
    "code-block": "Listing %s",
    "section": "Section %s",
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = [
    "custom.css",
]

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "WarpXdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "WarpX.tex", "WarpX Documentation", "WarpX collaboration", "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "warpx", "WarpX Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "WarpX",
        "WarpX Documentation",
        author,
        "WarpX",
        "WarpX is an advanced electromagnetic Particle-In-Cell code.",
        "Miscellaneous",
    ),
]


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"https://amrex-codes.github.io/": None}

# Setup the breathe extension
breathe_projects = {"WarpX": "../doxyxml/"}
breathe_default_project = "WarpX"

# Tell sphinx what the primary language being documented is.
primary_domain = "cpp"
# Tell sphinx what the pygments highlight language should be.
highlight_language = "cpp"

# Download AMReX & openPMD-api Doxygen Tagfile to interlink Doxygen docs
download_with_headers(
    url="https://amrex-codes.github.io/amrex/docs_xml/doxygen/amrex-doxygen-web.tag.xml",
    filename="../amrex-doxygen-web.tag.xml",
)
download_with_headers(
    url="https://openpmd-api.readthedocs.io/en/latest/_static/doxyhtml/openpmd-api-doxygen-web.tag.xml",
    filename="../openpmd-api-doxygen-web.tag.xml",
)

# Build Doxygen
subprocess.call(
    "cd ../; doxygen;"
    "mkdir -p source/_static;"
    "cp -r doxyhtml source/_static/;"
    "cp warpx-doxygen-web.tag.xml source/_static/doxyhtml/",
    shell=True,
)

suppress_warnings = ["bibtex.duplicate_label"]


def setup(app):
    """Post-process the reST that autodoc-pydantic generates for pydantic PICMI models
    (we do not reimplement any autodoc internals). Two passes:

    1. Insert ``Parameters`` / ``Methods`` / ``Attributes`` / ``Properties`` rubric
       headers between the groupwise member groups, so the long field list is visually
       separated from the methods and properties.
    2. Strip the ``:type:`` / ``:value:`` of class attributes whose value is just an
       object repr (e.g. the ``extension`` handle), so they render as a bare name instead
       of ``extension: ClassVar[Any] = <... object>``.

    Parameters are shown with their user-facing name, i.e., their alias (e.g.,
    ``warpx_break_signals``) instead of their field name (``break_signals``). Also use
    that name to sort the parameters and in the table of contents.
    """
    import re

    from sphinxcontrib.autodoc_pydantic.directives.autodocumenters import (
        PydanticFieldDocumenter,
        PydanticModelDocumenter,
    )
    from sphinxcontrib.autodoc_pydantic.directives.directives import PydanticField

    # Directive emitted for each member type -> rubric label (groupwise order).
    group_labels = [
        (".. py:pydantic_field::", "Parameters"),
        (".. py:method::", "Methods"),
        (".. py:attribute::", "Attributes"),
        (".. py:property::", "Properties"),
    ]
    object_repr = re.compile(r":value:\s*<.* object.*>")

    class GroupedPydanticModelDocumenter(PydanticModelDocumenter):
        def sort_members(self, documenters, order):
            documenters = super().sort_members(documenters, order)
            if (
                order == "groupwise"
                and self.config.autodoc_pydantic_field_swap_name_and_alias
            ):
                fields = self.object.model_fields

                def user_facing_name(documenter):
                    name = documenter.name.rsplit(".", 1)[-1]
                    field = fields.get(name)
                    if isinstance(documenter, PydanticFieldDocumenter) and field:
                        return field.alias or name
                    return name

                documenters.sort(
                    key=lambda entry: (
                        entry[0].member_order,
                        user_facing_name(entry[0]),
                    )
                )
            return documenters

        def document_members(self, all_members: bool = False) -> None:
            result = self.directive.result
            start = len(result.data)
            super().document_members(all_members)

            # Pass 2: drop ``:type:``/``:value:`` for object-repr attributes.
            to_delete = []
            i = start
            while i < len(result.data):
                if result.data[i].lstrip().startswith(".. py:attribute::"):
                    opts, j = {}, i + 1
                    while j < len(result.data):
                        m = re.match(r":(\w+):", result.data[j].strip())
                        if not m:
                            break
                        opts[m.group(1)] = j
                        j += 1
                    if "value" in opts and object_repr.search(
                        result.data[opts["value"]].strip()
                    ):
                        to_delete += [opts[k] for k in ("type", "value") if k in opts]
                    i = j
                else:
                    i += 1
            for idx in sorted(to_delete, reverse=True):
                del result[idx]

            # Pass 1: insert group rubrics before the first member of each type.
            insertions = []
            seen = set()
            for i in range(start, len(result.data)):
                stripped = result.data[i].lstrip()
                for prefix, label in group_labels:
                    if stripped.startswith(prefix) and label not in seen:
                        seen.add(label)
                        line = result.data[i]
                        indent = line[: len(line) - len(stripped)]
                        insertions.append((i, indent, label))
            for i, indent, label in reversed(insertions):
                src, offset = result.info(i)
                result.insert(i, "", src, offset)
                result.insert(i, f"{indent}.. rubric:: {label}", src, offset)
                result.insert(i, "", src, offset)

    class UserFacingNamePydanticField(PydanticField):
        def _toc_entry_name(self, sig_node):
            # autodoc-pydantic swaps the field name with the alias only in the signature
            entry = super()._toc_entry_name(sig_node)
            alias = self.options.get("alias")
            if (
                entry
                and alias
                and self.pyautodoc.get_value("field-swap-name-and-alias")
            ):
                name = sig_node["_toc_parts"][-1]
                if entry.endswith(name):
                    entry = entry[: -len(name)] + alias
            return entry

    # The classes of each kind, e.g., the field solvers, which the types of the parameters name
    # (``PICMI_AnySolver``): the classes of the standard and the WarpX classes deriving from them.
    import types as _types

    from docutils import nodes
    from docutils.parsers.rst import Directive
    from docutils.statemachine import StringList

    import picmistandard
    import pywarpx.picmi

    picmi_kinds = {
        name: value
        for name, value in vars(picmistandard).items()
        if name.startswith("PICMI_Any") and isinstance(value, _types.UnionType)
    }

    def warpx_classes_of_kind(union):
        return sorted(
            name
            for name, value in vars(pywarpx.picmi).items()
            if isinstance(value, type)
            and value.__module__ == "pywarpx.picmi"
            and issubclass(value, union.__args__)
        )

    class PicmiKinds(Directive):
        """Document the classes that each type alias of the PICMI standard accepts in WarpX"""

        def run(self):
            lines = []
            for name, union in picmi_kinds.items():
                classes = warpx_classes_of_kind(union)
                if not classes:
                    continue
                lines += [
                    f".. py:data:: picmistandard.{name}",
                    "",
                    "    "
                    + ", ".join(f":py:class:`~pywarpx.picmi.{c}`" for c in classes),
                    "",
                ]
            node = nodes.section()
            self.state.nested_parse(StringList(lines), self.content_offset, node)
            return node.children

    def resolve_picmi_kinds(app, env, node, contnode):
        # the types name the aliases of the standard, which are documented above as data
        target = node.get("reftarget", "")
        if node.get("refdomain") == "py" and target.rsplit(".", 1)[-1] in picmi_kinds:
            return env.get_domain("py").resolve_xref(
                env, node["refdoc"], app.builder, "obj", target, node, contnode
            )
        return None

    app.add_directive("picmi-kinds", PicmiKinds)
    app.connect("missing-reference", resolve_picmi_kinds)

    app.setup_extension("sphinxcontrib.autodoc_pydantic")
    app.add_autodocumenter(GroupedPydanticModelDocumenter, override=True)
    app.add_directive_to_domain(
        "py", "pydantic_field", UserFacingNamePydanticField, override=True
    )
